# Generated by Django 3.2.6 on 2021-09-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=500)),
                ('tweet_time', models.DateTimeField(null=True)),
                ('tweet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_from', to='myapp.user')),
            ],
        ),
    ]
