# Generated by Django 3.2.6 on 2021-09-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_time',
            new_name='time',
        ),
    ]
